version: "3.8^"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - net1

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    user: app
    volumes:
      - ./be:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/conf.d/php.ini-development:/usr/local/etc/php/php.ini:ro
    depends_on:
      - nginx
      - database
    networks:
      - net1
    environment:
      - APP_URL=http://api.localhost/
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=card_game_recruitment
      - DB_USERNAME=root
      - DB_PASSWORD=example

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./fe:/app
    depends_on:
      - nginx
      - database
      - backend
    networks:
      - net1

  database:
    image: mysql:8.0.35
    networks:
      - net1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=card_game_recruitment
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    networks:
      - net1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: example
volumes:
  mysql_data:

networks:
  net1: